### ISSUE TITLE
HTTP headers must be handled in case-insensitive manner

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-guide#103]
According to the [spec](https://www.rfc-editor.org/rfc/rfc7230#section-3.2), HTTP headers are case-insensitive.

The section REST guide [section](https://www.belgif.be/specification/rest/api-guide/#reserved-HTTP-headers) that covers HTTP headers should probably mention this?

Some middleware or tools can alter the casing of the HTTP headers, e.g. normalize them to lowercase. The application should therefore always treat HTTP headers in case-insensitive manner. e.g. in java: HttpServletRequest.getHeader(name) is OK, but watch out with methods like HttpServletRequest.getHeaderNames() because there it is your own responsibility to handle case-insensitivity.

**Comment by pvdbosch** [comment]
We could align with this zalando rule: http://opensource.zalando.com/restful-api-guidelines/#132

**Comment by pvdbosch** [comment]
WG agreed to align with Zalando's guideline. I'll work out a PR.

**Comment by pvdbosch** [comment]
created PR: https://github.com/belgif/rest-guide/pull/129
