### ISSUE TITLE
Add license to yaml files

### ISSUE THREAD

**Issue by aethy** [belgif/rest-guide#104]
The [OpenApi spec](https://spec.openapis.org/oas/v3.0.3#info-object) provides a "license" property in the Info Object to indicate the license type. As the belgif data types repositories already have a license (e.g. https://github.com/belgif/openapi-person-identifier/blob/master/LICENSE), maybe we should add this license in the yaml files too (for all belgif OpenAPI data types repositories).

**Comment by pvdbosch** [comment]
OK for WG to add Apache License 2.0 in all belgif openapi files.

**Comment by pvdbosch** [comment]
license added for employment-identifier (while changing it for another issue):
* https://github.com/belgif/openapi-employment-identifier/blob/master/src/main/openapi/employment/identifier/v1/employment-identifier-v1.yaml
* https://github.com/belgif/openapi-employment-identifier/blob/master/src/main/swagger/employment/identifier/v1/employment-identifier-v1.yaml

TODO for other openapi repos

**Comment by JDMKSZ** [comment]
I did it for 1 project: https://github.com/belgif/openapi-money/pull/4
If no remarks on that PR, I can do it for all the projects.
