### ISSUE TITLE
Handling undefined request parameters

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#110]
Formulate guidelines how an API should handle request parameters (in JSON body, query param or other) that aren't defined in OpenAPI.

For response elements, the [guideline](https://www.belgif.be/specification/rest/api-guide/#json-object) is for clients to ignore unknown properties to be able to evolve an API:

* `Service consumers should be aware that JSON objects can always be extended with additional JSON properties. This shouldn’t break the client code. The unknown properties must be ignored.`

For request parameters, this makes less sense however:

* having a request parameter ignored, means that the API won't fulfill the clients' expectations
* client implementation errors (with wrong param name) are more common than server-side and could go unnoticed

A (very specific) counter-example is an Angular paging table view component which may send additional query params to an API that can be safely ignored.

OpenAPI (JSON Schema) allows additional JSON properties by default, but for query parameters the situation is less clear.

Some interesting reads on this topic:
* https://opensource.zalando.com/restful-api-guidelines/index.html#109
* https://opensource.zalando.com/restful-api-guidelines/index.html#111
* https://github.com/OAI/OpenAPI-Specification/issues/568
* https://github.com/OAI/OpenAPI-Specification/issues/2511

**Comment by pvdbosch** [comment]
I couldn't find any option to configure commonly used openapi validators to fail on unknown JSON properties during request processing. 

One feature request was refused, saying that the schema should be changed instead to `additionalProperties: false` (e.g. with some pre-processing mechanism). This could be a hassle, cause this makes it difficult to use the same schema in request and response.
For query parameters, there's no way to specify in OpenAPI that unknown params should be (dis)allowed: https://github.com/OAI/OpenAPI-Specification/issues/2511

The Jackson library can be tuned to fail or ignore unknown JSON properties:
* failing on unknown properties is the default - https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/latest/com/fasterxml/jackson/annotation/JsonIgnoreProperties.html#ignoreUnknown--
* But not in Spring Boot, where they're ignored by default: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.html
**  it should be possible to change with  `spring.jackson.deserialization.fail-on-unknown-properties=true` configuration

**Comment by jpraet** [comment]
For consistency with https://github.com/belgif/rest-guide/issues/113, where issue types like `urn:problem-type:belgif:input-validation:mutuallyExclusiveParameters` and `urn:problem-type:belgif:input-validation:incompleteParameterGroup` are proposed:

maybe `urn:problem-type:belgif:input-validation:unknownParameter`?

Or should we add the *Request* to the other issue types? `urn:problem-type:belgif:input-validation:mutuallyExclusiveRequestParameters`, `urn:problem-type:belgif:input-validation:incompleteRequestParameterGroup`? That becomes quite verbose.

**Comment by pvdbosch** [comment]
I agree to drop "request", it's redundant with "input-validation"

**Comment by pvdbosch** [comment]
TODO: check if those using GCloud's APIGW can work together for implementation
Agreed to standardize on 'urn:problem-type:belgif:input-validation:unknownParameter'

(only in combination with in: query or in: body ; in : path => ResourceNotFound , in: header => unknown is allowed for http headers)

**Comment by jpraet** [comment]
Maybe an explicit mention should be made in the guidelines that this rule does not apply for API's that **consume** JSON events / notifications / webhooks via an HTTP POST? A new property added by the publisher of the events should not cause an error at the consumer side. Just like unknown properties should be ignored by the client when consuming data retrieved from a server.

**Comment by pvdbosch** [comment]
Unknown parameters should indeed be accepted in any webhook/callback request.
Webhooks/callbacks aren't documented in the guide however, and I don't yet know of any implementations following the guide using them; so mentioning them could cause more confusion than clarity.

We'd also have to clearly define semantics around callbacks (client, service, API, ...) to avoid confusion because the API (application programming *interface*) is defined by the sender of the events in such a case.

**Comment by jpraet** [comment]
Can this be closed? https://www.belgif.be/specification/rest/api-guide/#rule-req-valid
