### ISSUE TITLE
Should /doc and /doc/openapi.yaml be defined in the openapi.yaml contract?

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-guide#127]
I notice this is done in the https://github.com/belgif/rest-guide-example and wonder if it's a general recommendation to do this?

https://github.com/belgif/rest-guide-example/blob/1fcab76ddc385e01ab85dae96d5909f2b08f04a0/src/main/openapi/openapi.yaml#L385-L413

**Comment by pvdbosch** [comment]
Providing a /doc resource with a list of links isn't a general recommendation of the rest guide.  It might be removed in a future version of the example API.

Offering the /doc/openapi.yaml resource is recommended in https://www.belgif.be/specification/rest/api-guide/#rule-doc-refdata.
The guide doesn't say anything about listing it in openapi.yaml but an API Gateway may require it in order not to accept the request.
We've encountered some technical challenges with offering the documentation resources however, see: https://github.com/belgif/rest-guide/issues/96#issuecomment-1294994852 ; if they prove to difficult, they may warrant a deviation from the rule.
