### ISSUE TITLE
rename unknownParameter issue type

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#140]
A body or body part isn't considered a parameter (anymore) in OpenAPI 3.
Hence we ought to rename urn:problem-type:belgif:input-validation:unknownParameter into something else

**Comment by jpraet** [comment]
urn:problem-type:belgif:input-validation:unknownInput?

**Comment by pvdbosch** [comment]
WG decision: can be updated bc initial release of the rule was recent so very little chance on breaking something
Also clarify in rule that it applies to json properties in the request body, and doesn't apply to path parameters ( bc they don't have a name on the wire, and would result in a 404 instead)

**Comment by pvdbosch** [comment]
updated by #144. Has already been merged without PR review to limit risk on impact of change of input-validation issue type.

Keeping issue open for review next WG.

**Comment by pvdbosch** [comment]
Processed remarks on #144 in new (merged) PR #154
