### ISSUE TITLE
Refer to (and use) RFC 9457

### ISSUE THREAD

**Issue by JDMKSZ** [belgif/rest-guide#142]
The REST guide [refers to RFC 7807 ](https://www.belgif.be/specification/rest/api-guide/#error-handling) for defining problem details. This year, RFC7807 was superseded by RFC 9457, which improves the former. We should refer to the newer RFC and check for improvements to make.

**Comment by pvdbosch** [comment]
like in https://github.com/belgif/rest-guide/pull/139 :)

**Comment by JDMKSZ** [comment]
> like in #139 :)

So stupid, when [searching the issues](https://github.com/search?q=repo%3Abelgif%2Frest-guide+9457+&type=issues) I didn't find anything yet, but I should've looked in PR's also. Sorry for the duplicate.
