### ISSUE TITLE
Allow metadata JSON properties starting with _

### ISSUE THREAD

**Issue by jpraet** [belgif/rest-guide#149]
https://www.belgif.be/specification/rest/api-guide/#rule-jsn-naming

> do not use underscores (_), hyphens (-) or dots (.) in a property name, nor use a digit as first letter

Could a general exception to this rule be made for metadata properties?

e.g. HATEAOS "_links", and CBSS uses "_filters" to communicate to the client that certain fields that are defined in the contract, but they are not authorized for, have been filtered from the response.

**Comment by pvdbosch** [comment]
Underscores are currently not used for other metadata, like for pagination, href and self links.
HAL "_links" are not recommended in the guide: https://www.belgif.be/specification/rest/api-guide/#links 

You'd have the define when a property is considered metadata, i.e. is creation date or last modification date of a code in /refData considered metadata?

That said, the rule does allow deviations from other standards:
> Properties used from other standards, like OpenID Connect and OAuth2, are allowed to deviate from this rule.

This devation could apply to JSON-LD which defines metadata properties with the @ prefix.

**Comment by pvdbosch** [comment]
I know :) I meant to re-evaluate it (because "da's wel mss niet heel consistent"), but the matter wasn't really pressing at the time...

**Comment by jpraet** [comment]
FWIW, CBSS decided to return the applied data filters in a HTTP response header instead of a "_filters" property in the body.
