### ISSUE TITLE
Evaluate OpenAPI tooling

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#25]
In GitLab by @pvdbosch on Sep 7, 2018, 16:25

1) Test senya.io, stoplight.io, apicurio or any other interesting tool to author swagger files.

2) Evaluate code generation maven plugins: openapi-generator vs swagger codegen. 
Recommend one?

Comparison (WIP):

Swagger codegen:
* specifying explicitely `additionalProperties: true` was required to let generated Java classes support additional properties not specified in the Swagger file (untested on openapi-generator)
  * even with this specified, the generated code didn't work properly
* when generating fat swagger, creates top level types for inlined (non-Venetian-blind) types. It shouldn't. The generated types don't follow styleguide naming convention. (untested on openapi-generator)
* generated code's formatting a bit better
* invalid escaping for regexp: `@Pattern(regexp="\d{11}")` => doesn't compile, should be `@Pattern(regexp="\\d{11}") ` (tested with v3 of codegen)

openapi-generator:
* more actively developed
* unnecessary java imports, bad formatting in generated code - maybe fixable with some tuning
* `additionalProperties: true` has no effect
* 4.x use of allOf:
  * generate useless *AllOf classes for Swagger types inlined in an `allOf` composition. They are imported in the composite class but not used
  * no inheritance in generated code anymore when using `allOf` with a referenced type: e.g. InvalidParamProblem no longer extends Problem (see https://github.com/OpenAPITools/openapi-generator/issues/5097#issuecomment-591417573)
  * workaround for both: only specify base class in allOf and specify properties on same level like this:
` MyType: { allOf: [$ref: '#/components/schemas/T'], properties: { x:  {type: string}} } `
* converts `format: uri` to java.net.URI as of 4.1.0
* In 4.3.1: inline object types become java.lang.Object instead of proper generated type. Workaround: make them explicit (non-inline) types

Other notes:
* specifying an array of types, while valid JSON Schema, doesn't seem to be supported in OpenAPI
* `format: decimal` isn't part of the OpenAPI standards, and isn't supported for code generation
* Custom typemappings may be needed in maven config, e.g.
  * to get byte array as return type (e.g. when returning image) for `type: file` instead of default java.io.File:
`<typeMappings><typeMapping>file=byte[]</typeMapping></typeMappings>`
* all plugins: JAX-RS always returns a default http status code (200 for OK with body, 204 for OK without body). Only way to override is by generating `javax.ws.rs.core.Response` return types for all generated models.

3) Smals will share their extensions to the code generation plugin, adding proper support for additional properties to all generated classes.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Oct 5, 2018, 12:01

Most authoring tools seem to have difficulties with definitions referenced from external YAML files.

Some feedback from our developers:
* senya.io: IntelliJ plugin. 
  * Problems with external schemas in graphical view, though supported in text view (i.e. links can be followed)
  * marks some properties as faulty while they're valid OpenAPI 2.0: the 'examples' property in a Response Object, and a property defined without a type
* swagger editor: also problems with external references; (see [this issue](https://github.com/swagger-api/swagger-editor/issues/1409) and [this other issue](https://github.com/swagger-api/swagger-editor/issues/1630).
 * might be working if files are reachable by http instead file:///
 * Only tested with v3. Issue mentions swagger editor v2 might support it better than v3. 
* Stoplight is not free of charge, so didn't test
* apicur.io: only single file swagger. No switching between graphical and text representation. Still beta.

RepreZen is another paying alternative, but didn't try out yet.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Nov 23, 2018, 16:21

Latest 0.20 version of Senya works fine now. Tested with socialStatus API, with external files, both in text as UI mode.

I reported the bug concerning examples (as mentioned in #28) in Swagger and it got fixed.
Senya follows closely the OpenAPI 2.0 spec, which means that you have to use the MIME type as key of each example, matching one of the 'produces' MIME types. This means you can only specify a single example per response status code. For the socialStatuses API, we used to specify multiple examples using some free text description as key, as the Swagger editor didn't verify that they were MIME types.
The OpenAPI 3.0 spec does allow specifying multiple examples.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Dec 17, 2018, 11:54

KaiZen as eclipse plugin

SwaggerUI watcher https://github.com/moon0326/swagger-ui-watcher views in browser

can be added to list of tools in style guide

**Comment by pvdbosch** [comment]
In GitLab by @wsalembi on Jan 20, 2019, 12:09

Senya Editor for Intellij IDEA has become a paid plugin for https://senya.io/release-notes-1-0-0/ (48 euro/year)

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Jan 22, 2019, 10:15

updated the styleguide:
* split tools and references section, add some more description
* mention Senya is commercial
* add Zalando's IntelliJ plugin

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Jan 22, 2019, 11:53

changed title from **evaluate {-tools to author swagger files-}** to **evaluate {+swagger tooling+}**

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Jan 22, 2019, 12:11

Broadening scope of the issue to also include other tooling, like codegen.

For code generation from swagger, there are two plugins:
* swagger-codegen: https://github.com/swagger-api/swagger-codegen
* openapi-generator from OpenAPITools: https://github.com/OpenAPITools/openapi-generator (= fork of swagger-codegen)

Both still seem under active development, though openapi-generator seems to have more activity.
What are practical experiences with the plugins of the WG members? Do we recommend the openapi-generator one?

Some issues encountered by @VirginieHayot when using the swagger codegen:
* specifying explicitely `additionalProperties: true` was required to let generated Java classes support additional properties not specified in the Swagger file
* even with this specified, the generated code didn't work properly

Smals (@smals\-wisa ) developed an extension to the plugin, adding proper support for additional properties to all generated classes. It would be interesting to other WG members if this extension could be shared.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Feb 26, 2019, 13:50

Added WIP comparison between codegen plugin to issue description, everyone can contribute.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Feb 26, 2019, 13:50

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Feb 27, 2019, 12:14

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Feb 27, 2019, 12:17

Another codegen issue encountered with InvalidParamProblem; arrays of types cause property to be ignored during code generation: 

```
  InvalidParam:
    type: object
    properties:
      in:
        type: string
      name:
        type: string
      reason:
        type: string
      value:
        # allow all types, as type is mandatory. Known issue: property is ignored when using swagger codegen (see #25)
        type: [string, number, integer, boolean, array, object, 'null']
```

(from new problem-v1.yaml)

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Feb 27, 2019, 12:47

mentioned in commit 229c7e74dba6e1947003ffaff54724d73476b99d

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Mar 11, 2019, 09:50

Omitting `type` on the `value` property; this works with code generation to get Object type.

Having no `type` is valid [OpenAPI 2.0](https://stackoverflow.com/questions/47374980/schema-object-without-a-type-attribute-in-swagger-2-0) even though KaiZen (and maybe some other editors) indicates it as an error.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Mar 11, 2019, 10:05

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Mar 11, 2019, 10:08

added some more remarks on codegen plugin, after some testing.

The openapi-generator generates some weird warnings, but they can be ignored it seems.

```
[INFO] --- openapi-generator-maven-plugin:3.3.4:generate (Generate server stub model) @ ssh-citizen-web ---
[WARNING] Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[INFO] Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[INFO] NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[WARNING] Multiple schemas found, returning only the first one
[WARNING] Multiple schemas found, returning only the first one
[WARNING] Multiple schemas found, returning only the first one
[WARNING] Multiple schemas found, returning only the first one
[WARNING] Multiple schemas found, returning only the first one
[WARNING] Multiple schemas found, returning only the first one
[WARNING] Multiple schemas found, returning only the first one
```

For the `additionalProperties`, maybe it's sufficient to create a subclass of the generated class in most cases?

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Mar 13, 2019, 14:05

mentioned in commit 7abe48a6b800c15a051fe547cfaa2d05ac4af27c

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Mar 13, 2019, 14:57

mentioned in commit 11c61873b9c8cdf688b0ab32c6aa1a4aef63f219

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on May 10, 2019, 09:26

mentioned in commit 9c3e545b7ee3e944566a9450a08eb7adc3f48e62

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on May 10, 2019, 09:26

mentioned in commit c373a75ab5d6728c9bbe68fec717885da4dcf789

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on May 10, 2019, 09:26

mentioned in commit a9ffd2dd5f6570a218b1e63a38ad5947d28e51f3

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Jun 20, 2019, 09:39

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @ehealth-eh053 on Jun 24, 2019, 11:09


```
 responses:
        '201':
          description: Created
        default:
          description: Failure server response
          schema:
            $ref: "./specs/ehealth-api-problem.yaml#/definitions/Problem"
```

When using the openapi-generator-maven-plugin the generated source doesn't use the correct code for the default errors.
```
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Created"),
        @ApiResponse(code = 200, message = "Failure server response", response = Problem.class) })
```

**Comment by pvdbosch** [comment]
In GitLab by @jimmy.praet on Jul 15, 2019, 11:56

I have some issues with the openapi-generator-maven-plugin (3.3.4):

```
      parameters:
        - in: query
          name: types
          type: array
          items:
            type: string
            enum: # cannot use a $ref here in Swagger 2.0
              - CLASSIC
              - BIIP35
              - BIIP38
              - BIIP77
              - PCSA
              - MUNICIPALITY
              - PROVINCE
```

This generates the following:

```
    @GET
    @Produces({ "application/json;charset=utf-8" })
    @ApiOperation(value = "Retrieve the list of CLSM partners", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Partners.class) })
    Response getPartnerList(@QueryParam("active")    Boolean active,@QueryParam("types")  @DefaultValue("new ArrayList<>()")   List<String> types);
```

The `@DefaultValue("new ArrayList<>()")` is problematic. When I don't supply a value for the parameter, I get a List<String> in my implementation method containing 1 string element "new ArrayList<>()".

I tried configuring a default in the swagger file, but this didn't make any difference.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Aug 8, 2019, 12:22

Another pitfall encountered with generated code is that JAX-RS always returns a default http status code (200 for OK with body, 204 for OK without body).

The status codes in the Swagger `ApiResponse` annotations are ignored by JAX-RS; they're only used when a swagger file is generated from the code when doing code-first development.

To allow for other response codes, you can configure `<returnResponse>true</returnResponse>` in the maven plugin, which will then let all generated methods return a `javax.ws.rs.core.Response` on which status code and response body can be set.
You'll loose type-safety of return types, but there doesn't seem to be a nicer way in JAX-RS.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Aug 23, 2019, 11:13

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Aug 23, 2019, 11:15

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Aug 23, 2019, 11:15

Some results of tests with openapi generator 4.1.0 added to issue description:

* 4.0.3 and 4.1.0 generate useless *AllOf classes for Swagger types inlined in an `allOf` composition. They are imported in the composite class but not used
* 4.1.0: Java classes don't seem to use inheritance anymore when using `allOf` with a referenced type (not yet tested on 4.0.x): e.g. InvalidParamProblem no longer extends Problem
* converts `format: uri` to java.net.URI as of 4.1.0

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Aug 23, 2019, 12:12

changed the description

**Comment by pvdbosch** [comment]
Willem has good initial experiences with stoplight.io, with support of custom styleguide validations ("spectral" functionality), which can also be used in other tools like maven.

**Comment by pvdbosch** [comment]
For the issues with the use of `allOf`, we should open issues on openapi-generator GitHub. If no reaction, we could try to workaround in a customization of the plugin.

Smals provides some handy [customizations (requires gCloud membership)](https://git-cicd.gcloud.belgium.be/rest/openapi-generator).

**Comment by jpraet** [comment]
I'm also encountering an issue with openapi-generator-maven-plugin 3.3.4 and a type definition called "File": the type is not generated, and the class referencing the type uses java.io.File instead. This is for an API for managing batch executions. I can work around it by using a different name like "BatchFile".

**Comment by pvdbosch** [comment]
done some experimenting with "readOnly" parameter:
* it isn't supported in the UI of Stoplight, only in text mode
* in SwaggerUI, readOnly is only shown on properties with simple types, not on object types
* Java code generation ignores readOnly (tested openapi-generater 3.3 and 4.2)
* OpenAPI syntax gets a bit weird when using readOnly on a property with a $ref type (https://github.com/OAI/OpenAPI-Specification/issues/1671), requires use of allOf :

```
  "address": {
      "readOnly": true,
      "allOf": [
         {"$ref": "#/components/schemas/Address"}
       ]
    },
```

**Comment by pvdbosch** [comment]
eHealth uses https://www.npmjs.com/package/api-spec-converter to convert from OpenAPI 2.0 to 3.0, because it gives better results with code generation. Some manipulation on its input 2.0 file may be required for it to work correctly.

**Comment by jpraet** [comment]
Up until openapi-generator 3.3.4, InvalidParamProblem extends Problem in the generated code.
As of 4.0.0 it uses composition. Then in 4.3.0 it went back to inheritance, and in 4.3.1 they ["fixed that regression"](https://github.com/OpenAPITools/openapi-generator/issues/5876) and went back to composition.

The spec says that [allOf is intended for model composition, and does not imply a hierarchy between the models](http://spec.openapis.org/oas/v3.0.3#composition-and-inheritance-polymorphism). For type hierarchies, a discriminator should be used.

I did found out that you can trick the openapi-generator into generating inheritance by specifying a dummy discriminator in the problem schema, pointing to a non-existing property. Probably not a good idea to do that though.

**Comment by pvdbosch** [comment]
I'll demo on the WG tomorrow a Java support library on which @jpraet is working on for CBSS. It may be interesting for others as well.

It provides: 
* Exception types for each of the standardized gCloud problem types
* supports conversion to these types using Jackson
* for JAX-RS specifically:
  * creates Bad Request Problem responses automatically for Bean Validation errors compliant to the REST guide
  * adds /doc resource with the swagger file, swagger-ui, and other static doc pages
  * sets some Jackson JSON parsing defaults (omit null values in serialization, Java 8 datatime types, ...) and Problem conversion

Client-side, we're trying out Microprofile Rest Client and RestEasy REST client on JBoss, which still have some limitations.

We're also using the library to work with problems in Apache Camel and on Axway APIGW.

**Comment by pvdbosch** [comment]
In openapi-generator 4.x, using allOf like below seems to get the desired result with inheritance:
```
    S:
      allOf:
        - $ref: '#/components/schemas/T'
      properties:
        x:
          type: string
        y:
          type: string
```
Still seems like a deprecated behavior that might change in openapi-generator 5.x. 
We'll change InvalidParamProblem to use this type of definition. It seems equivalent according to OpenAPI spec, but gives better results for code generation.

**Comment by pvdbosch** [comment]
REST WG is OK with the change in previous comment of the InvalidProblem definition.

Examples of use of "allOf" and "properties" as sibling elements seem to be supported by JSON Schema, cfr examples in the standard:
* https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.D.2
* https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.E

OpenAPI 2.0 standard doesn't mention this kind of usage explicitly, but OpenAPI 3.1 will explicitly be a superset of JSON Schema v2019-09 so we're future proof. It also works for Swagger/OpenAPI tooling (tested with openapi-generator and StopLight Studio).

**Comment by pvdbosch** [comment]
StopLight Studio is incorrectly listed as Open Source in the REST guide. Its GitHub repo only contains the documentation as open source, and binary releases.  So changing it to "Commercial editor with a free version".
They're capping max users and max projects in the free edition, but I think that's only about the "collaborative workspace" features.

**Comment by pvdbosch** [comment]
openapi-generator 5.x doesn't generate classes with inheritance anymore without use of discriminator. Seems no easy workaround for this, so we're sticking on 4.3 at CBSS. There's some ongoing discussion about this behavior change, and some other talk about creating openapi extension keywords to modify code generation for such cases.

We encountered another problem with JAX-RS/Jackson code generation for GenderCode type of person-v1.yaml, which is a number enum:
* generates JSON String instead of number: `@JsonValue String toString()`
* doesn't work when the type is used as query param because no conversion method from string to enum class foreseen

We now use a non-generated class for this.

**Comment by pvdbosch** [comment]
In Visual Studio Code, Code42's "OpenAPI (Swagger) Editor" plugin works quite well; it supports code completion, external refs and SwaggerUI preview. 
Minor issue in SwaggerUI preview: external ref type names are shown with an escaped version of their full absolute path, so makes them a bit less readable.

**Comment by jpraet** [comment]
A PR https://github.com/OpenAPITools/openapi-generator/pull/14172 has been merged in openapi-generator that supports configuration of a REF_AS_PARENT_IN_ALLOF "normalizer", which should enable use of inheritance.

**Comment by pvdbosch** [comment]
@jpraet, that's interesting! We can check how to best apply this (mainly to Problem types).

From what I can see, we'll be able to choose between:
* configure the normalizer, which makes "x-parent: true" the default for $refs in an allOf. This leaves the schemas unchanged.
* adding an "x-parent: true" property explicitly to the schema object that should become parent class
* create an interface type and add "x-implements: <interface name>" to the schema (already supported in current release). This option limits the schema to a specific programming language or usage

**Comment by jpraet** [comment]
Another observation with openapi-generator-maven-plugin: when using an enum as a query param, only UPPER_CASE values are accepted at runtime. This is fixed in 6.x: https://github.com/OpenAPITools/openapi-generator/pull/7494

**Comment by jpraet** [comment]
openapi-generator-maven-plugin 6.3.0 is released.

Using allOf refs as parent can be enabled globally by adding `<openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true</openapiNormalizer>` to the plugin configuration.

Alternatively, "x-parent: true" can be added to the schema objects to be used as parent class.

**Comment by pvdbosch** [comment]
PR #123 makes some changes to list of OpenAPI tooling:
Removed tooling with no releases last couple of years: Reprezen/Kaizen, swagger-ui-watcher, senya.io
Added IntelliJ bundled ultimate and 42Crunch plugins

**Comment by jpraet** [comment]
> In openapi-generator 4.x, using allOf like below seems to get the desired result with inheritance:
> 
> ```
>     S:
>       allOf:
>         - $ref: '#/components/schemas/T'
>       properties:
>         x:
>           type: string
>         y:
>           type: string
> ```
> 
> Still seems like a deprecated behavior that might change in openapi-generator 5.x. We'll change InvalidParamProblem to use this type of definition. It seems equivalent according to OpenAPI spec, but gives better results for code generation.

In the latest openapi-generator versions 6.5.0 and 6.6.0, this no longer generates inheritance, even with `<openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true</openapiNormalizer>`.

But with 

 ```
     S:
       allOf:
         - $ref: '#/components/schemas/T'
         - type: object
           properties:
             x:
               type: string
             y:
               type: string
```

it works.

**Comment by jpraet** [comment]
I've reported an issue for the openapi-generator-maven-plugin regression mentioned above: https://github.com/OpenAPITools/openapi-generator/issues/16389

**Comment by pvdbosch** [comment]
New version 7.0.0 of the openapi-generator seems to work fine:
* useless allOf classes aren't generated anymore for inline types
* parent classes are used by setting `<openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true</openapiNormalizer>` (first $ref is parent) or by adding `x-parent: true` on the parent class. The x-parent setting has precedence over the normalizer.

We could add `x-parent: true` to the belgif Problem type, but I think activating the `REF_AS_PARENT_IN_ALLOF=true` could be the default behavior what most developers want. Its behavior can still be overridden by `x-parent`, though it becomes more difficult when reusing external schemas.

**Comment by jpraet** [comment]
> New version 7.0.0 of the openapi-generator seems to work fine:
>     * parent classes are used by setting `<openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true</openapiNormalizer>` (first $ref is parent) or by adding `x-parent: true` on the parent class. The x-parent setting has precedence over the normalizer.

From my testing and with the feedback I got from https://github.com/OpenAPITools/openapi-generator/issues/16389, you'll need to set `<openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true,REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true</openapiNormalizer>`
when the openapi style of combining allOf with object properties is used, like

```yaml
    S:
      allOf:
        - $ref: '#/components/schemas/T'
      type: object
      properties:
        x:
          type: string
        y:
          type: string
```

**Comment by jpraet** [comment]
> IntelliJ Ultimate 2023.2 switched the OpenAPI preview from SwaggerUI to redocly. It has a couple UX regressions IMO: overview of all operations is less at-a-glance, and schemas aren't listed separately from the operations.

There's a button to switch to SwaggerUI, bit it unfortunately keeps opening the preview in Redocly by default.

![image](https://github.com/belgif/rest-guide/assets/2212615/1d0002ef-c60a-4f0b-b034-c44e537ba401)

Redocly also crashes on this:

```yaml
  /health:
    $ref: cbss/common/v1/common-v1.yaml#/paths/~1health
```

I think because of https://github.com/Redocly/redoc/issues/2337

Other sidenote: I also get "Unresolved reference" errors now in the openapi editor since the last IntelliJ IDE upgrade.

```yaml
        default:
          $ref: belgif/problem/v1/problem-v1.yaml#/components/responses/ProblemResponse
```

It's happy when I add quotes

```yaml
        default:
          $ref: "belgif/problem/v1/problem-v1.yaml#/components/responses/ProblemResponse"
```

**Comment by jpraet** [comment]
As of openapi-generator 6.5, optional array properties no longer get initialized with an empty list (https://github.com/OpenAPITools/openapi-generator/issues/15891). From the ticket, it seems unsure whether that change in behavior is either intentional, or a regression.

While we don't want implementation quirks in tooling inform our decisions on API guidelines, it does raise the question for me whether we should spend more thought on making array properties required vs optional.

For example: the items property of collection resources.
The https://www.belgif.be/specification/rest/api-guide/#rule-col-repres states:
> In case the collection is empty, the items property MUST have an empty array as value.

So shouldn't the items property be marked required then in the example openapi spec?
https://github.com/belgif/rest-guide/blob/66606c8b28be5dff184eca9e61eaf8c84525ffb2/guide/src/main/asciidoc/resources-collection.adoc?plain=1#L88-L98

**Comment by pvdbosch** [comment]
I agree, I don't see any use case in which "items" array shouldn't present in a collection.
When the array property is marked as required, does openapi-generator initialize it to an empty list in version >= 6.5?

I think the new behavior of the openapi-generator is consistent; other types are also initialized as null when the property is absent. 

We also consider null and absent JSON properties as equivalent, while an empty array is different.

> Rule: Null values [[jsn-null]](https://www.belgif.be/specification/rest/api-guide/#rule-jsn-null)
> 
> Properties with a null value SHOULD be stripped from the JSON message.
> 
> A notable exception to this rule are JSON Merge Patch requests, in which a null value indicates the removal of a JSON property.
> 
> Note that this rule doesn’t apply to empty values (e.g. empty strings "" or empty arrays []) as they are considered different from a null value.

**Comment by pvdbosch** [comment]
some more openapi-generator 7.0 findings:
* additionalProperties are sometimes now generated as "class X extends HashMap<String, Type>", but not for the spring generator where it uses @JsonAnyGetter and @JsonAnySetter methods - https://github.com/OpenAPITools/openapi-generator/pull/11572 ; hopefully this gets applied in future releases to JAX-RS as well
* plugin generates some markdown files with documentation now

**Comment by jpraet** [comment]
> When the array property is marked as required, does openapi-generator initialize it to an empty list in version >= 6.5?

Yes

**Comment by jpraet** [comment]
> > IntelliJ Ultimate 2023.2 switched the OpenAPI preview from SwaggerUI to redocly. It has a couple UX regressions IMO: overview of all operations is less at-a-glance, and schemas aren't listed separately from the operations.
> 
> There's a button to switch to SwaggerUI, bit it unfortunately keeps opening the preview in Redocly by default.

As of 2023.2.2, IntelliJ remembers your choice of preview tool.

**Comment by wsalembi** [comment]
In v7.0.0, model classes have a new constructor with required properties. If this constructor is a single arg, Spring boot/Jackson applies a mapping so that  fields with the 



 ```
-- EXPECTED

"municipality": {
   "name": "Antwerp"
} 

-- ACCEPTED
"municipality": "Antwerp"


-- because of model.Municipality(String name) {} constructor
 ```


 ```
-- EXPECTED

"country": {
   "countryNisCode": 150
} 

-- REFUSED with error "country is not of type int" 
 "country": "Belgium"

-- because of model.Country(Integer countryNisCode) {} constructor
 ```

**Comment by pvdbosch** [comment]
to investigate: differences between typeMappings/schemaMappings/importMappings in openapi-generator

**Comment by pvdbosch** [comment]
I've created a couple GitHub Discussions to replace this issue, in order to keep the issue backlog clean and the discussions more focused:
* #145 
* #146 
* #147 

Please continue to exchange your ideas and experiences in these discussions.
