### ISSUE TITLE
Impact analysis of introducing OpenAPI v3

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#31]
In GitLab by @wsalembi on May 13, 2019, 11:02

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on May 17, 2019, 20:08

WIP list of impact on styleguide: 

* nullable support => something better than empty placeholder type for JSON Merge Patch?
* media type possible per operation => remove default produces: application/problem+json?
* support for multiple (simple) types => E.g. embedded additionalProperties
* more ways to provide examples in openapi => update guidelines
* default file name swagger.yaml => openapi.yaml
* more places where `deprecated` can be specified

other impact:
* swagger validation rules (plugin doesn't support OpenAPI 3.0 at the moment)

**Comment by jpraet** [comment]
Can this be closed?

**Comment by pvdbosch** [comment]
Opened new issues for open points:
* examples: https://github.com/belgif/rest-guide/issues/188. The remaining ones without ticket
* nullable: https://github.com/belgif/rest-guide/issues/189

I haven't seen much use cases where the links feature would be worthwhile; so not following that up
