### ISSUE TITLE
styleguide, schemas and vocabularies platforms

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#35]
In GitLab by @pvdbosch on Jun 18, 2019, 21:31

On the 'plenaire', the issue on how we best manage and publish our work was brought up again.

Move to GitHub For source control and issue management: 
* accessibility: 
  * gcloud gitlab is on a closed network
  * hurdle to let regions get access, private organizations, and originally hurdle for NR as well
* visibility: using github increases visibility (like done for digipolis, zalando and Informatie Vlaanderen)

_status:_

- [x] migration to github
- [x] change Jenkins gCloud to access GitHub. Currently GitLab is still used as mirror for builds. To test if Jenkins can access internet (if so, probably only with IAP http proxy)
- [ ] gitlab to be archived or limit visibility and deactivate issue&wiki (depending on Jenkins solution)

For publishing REST guide and schemas to a website:
* consistency with functional WG (vocabularies) is desirable
  * vocabularies currently use vocab.belgif.be RDF namespace but aren't published yet
* the websites https://www.belgif.be/ and https://vocab.belgif.be/ aren't very inviting though
  * ... but may encourage participation of regions
  * a link exists from https://www.belgif.be/ to the REST guide on https://www.gcloud.belgium.be/rest/

Binaries (maven) repository:
* styleguide validation rules: maven central repo?
* do we publish Swagger/OpenAPI schemas on maven repo as well?

Organizational:
* for functional WG, plans are being made to move the work under the ICEG umbrella
  * to make it easier for the regions to participate; and enable reuse of tooling used by data.vlaanderen.be

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Jun 18, 2019, 21:52

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Nov 28, 2019, 13:00

changed the description

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Nov 28, 2019, 13:06

On next WG meeting, I'd like to decide on the point of source control and issue management, because gCloud GitLab is difficult for regions and others to participate.

@marc.bruyland : could we consider moving to a new "rest-guide" repo on https://github.com/belgif ?
@wsalembi : is it possible to configure gCloud jenkins to build from this location?

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Dec 11, 2019, 15:00

migrate to github, I will contact Bart Hanssens to create repo.
Issues: manual migration or scripted?

Jenkins job : check if we can access github, if not temporarily sync both.

Access: one access manager per institution will be added. I'll sent an e-mail once repo is ready.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Dec 12, 2019, 16:59

I did a test run of the migration to github using this script: https://github.com/piceaTech/node-gitlab-2-github 

I had to modify a bit for compatibility with the fediap http proxy, but then got it working.

Test run migration is on : https://github.com/kszbcss/rest-guide-migration

Results are quite good:
* issues are migrated
  * issue numbers are preserved
  * the issue and comments have new dates and author is the migrator
  * but a comment is added each time with original user and tista on GitLab
  * labels are migrated
* pull requests are migrated
  * just an error on pull request !6 because it doesn't have any commits
* wiki is not migrated. Needs to be done manually (probably easiest) or with [another script](https://github.com/wollzelle/gitlab-github-migrate)
* it's possible to map gitlab users to github ones in input of script

I'll send a mail to ask for github user names, so I can use the user mapping and launch the script for the belgif repo.

**Comment by pvdbosch** [comment]
Migration done. Wiki was migrated manually.

Notes:
* closed GitLab Merge Requests were migrated of which to Git branch didn't exist anymore are migrate to GitHub issues instead of pull requests
* wiki: issue numbers aren't displayed as hyperlinks
* wiki attachments haven't been migrated
* GitLab is still used as a mirror to trigger build & publish to https://www.gcloud.belgium.be/rest/ using gcloud Jenkins.

To do:
* deactivate wiki, merge requests and issues  on GitLab
* find a solution for wiki attachments:
  * [CBSS status codes](from https://git-cicd.gcloud.belgium.be/rest/styleguide/wikis/existing-error-codes)
  * [code examples on wiki home page](https://git-cicd.gcloud.belgium.be/rest/styleguide/uploads/982e48558e7f6aeb75eff8e8bb3a2995/contract-first-java-export-ehealth.zip)

**Comment by pvdbosch** [comment]
attachments in wiki can be added by adding them to the wiki git repo (https://github.com/belgif/rest-guide.wiki.git) and then linking to them.

**Comment by pvdbosch** [comment]
styleguide is built by Jenkins from GitHub now. Build is triggered manually, it isn't on-push anymore. But I currently have insufficient permissions to trigger build on Jenkins.

After this is OK, the old gitlab repo can be archived.

**Comment by pvdbosch** [comment]
Jenkins is OK now. Did a new publication of the guide from GitHub sources using Jenkins.
Asked @wsalembi to archive old GitLab repo, then this issue may be closed.

Publication of the OAS schemas is continued in #27.

**Comment by wsalembi** [comment]
old GitLab repo archived
