### ISSUE TITLE
Use static rule identifiers

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#38]
In GitLab by @pvdbosch on Nov 14, 2019, 12:17

Change the REST guide to use static rule numbers instead of autogenerated ones.

This was decided in work group of June 2019.

**Comment by pvdbosch** [comment]
anyone up for the task can take this ticket

**Comment by jpraet** [comment]
A static id anchor for each rule would be very helpful, as I've oftentimes wanted to reference a specific rule in the REST guide. 
Maybe there is no need for rule _numbers_ though? Having static rule numbers would look weird when a new rule is added somewhere in the document. You'll see rule 1, 2, then somehow rule 62, and then back to 3, 4, ... when reading through the REST guide?

**Comment by pvdbosch** [comment]
Right, we could change the rule macro to always create an anchor.

Are we OK dropping the rule numbering then? 
We could replace them with textual codes if that would be useful, e.g. 

"Rule : Default media types [dmt]"
"Rule : Paging over a large collection​ [pag]"

To discuss next WG.

**Comment by pvdbosch** [comment]
Discussed on WG:

Add an anchor id to the macro to generate the rule title, e.g. "dmt", "emb-sub", ...
Macro will generate anchor prefixed with "rule-" e.g. #rule-emb-sub
The anchor id will be added to the rule title and a link should be available when hovering over the rule title (like chapter titles), e.g. "Rule: Embedding subresources [emb-sub]" ; so the abbreviated form can be displayed in reports from tooling like the styleguide validation tool.

**Comment by pvdbosch** [comment]
Created asciidoc extension for a rule block, in PR #111 ; still need to convert all the rules

**Comment by pvdbosch** [comment]
converted some of the rules in the PR. Rule identifiers picked max 7 char long. Also made some layout changes on rule title. Validate on next WG if OK, before converting rest of the rules.

![image](https://user-images.githubusercontent.com/7010035/223721094-232f77b6-4704-48cd-adad-7ea9aa37393b.png)

**Comment by pvdbosch** [comment]
all rules updated. Merged to master, will be part of next styleguide update
