### ISSUE TITLE
update tables with http status codes and verbs

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#40]
In GitLab by @pvdbosch on Nov 14, 2019, 15:48

Our REST guide sections about http status codes and methods could be improved. 
E.g. tables summarizing giving an overview like these 2 tables:
   https://github.com/digipolisantwerpdocumentation/api-requirements#http-verbs

Maybe some overlap can be removed of the HTTP methods section with the Resources (Document/Collection) sections.
They're not always consistent either, e.g. 7.6 DELETE lists status code 200 but 8.2 only lists "200 OK" for GET and PUT.

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Nov 25, 2019, 10:46

marked #43 as a duplicate of this issue

**Comment by pvdbosch** [comment]
In GitLab by @pvdbosch on Nov 25, 2019, 10:50

Some more inconsistenties of status codes, listed by @smals-chlo (merged from #43 ).

In the Rest guidelines, there are 2 sections describing the allowed https codes per method: 

A) https://www.gcloud.belgium.be/rest/#status-codes
Column: Operation 

B) https://www.gcloud.belgium.be/rest/#http-methods
Below each method 

It seems that some allowed codes are missing and also the info is not always consistent in the 2 sections. 

Some examples: 

1) https://www.gcloud.belgium.be/rest/#delete
Only 200 is present. 
vs
https://www.gcloud.belgium.be/rest/#2xx-success
Also 204 is allowed for Delete

2) https://www.gcloud.belgium.be/rest/#get
Why not also 400 and the 5XX family? 

3) https://www.gcloud.belgium.be/rest/#post
201 Created is present 
vs
https://www.gcloud.belgium.be/rest/#2xx-success
Only PUT for 201.

**Comment by pvdbosch** [comment]
Reviewed changes in PR #64 :
* OPTIONS, to retrieve list of allowed HTTP methods, could also apply to Controller. Should status code 200 be removed? Probably always 204 No Content.
* some minor remarks on the structure:
  * we still have quite a bit duplicated info on status codes. Maybe remove the status codes list from the HTTP methods section? The bits that aren't already elsewhere in the document, could be added to the "Most used response codes" sections in resources chapter.
  * For the new "​​How to use GET/POST/..." tables: I think it'd be handy to merge them into a single overview table at the beginning of the HTTP methods chapter

**Comment by smals-chlo** [comment]
Hello @pvdbosch , 
Thank you for the remarks. 

- _OPTIONS, to retrieve list of allowed HTTP methods, could also apply to Controller_ --> OK, I will adapt. 
- _OPTIONS: Should status code 200 be removed? Probably always 204 No Content_--> Response payload is possible to be sent with OPTIONS, so I think 200 could be used as well. 
- _we still have quite a bit duplicated info on status codes_ --> It seems like duplicated info, but to me it's an additional way to navigate to status codes (from collection, document, methods to status codes and from status codes to methods)
- _For the new "​​How to use GET/POST/..." tables: I think it'd be handy to merge them into a single overview table_ --> At Smals the preference was to split the table, but we can elaborate on this tomorrow. 

In any case, I will give an overview of the changes tomorrow and we can align on these and maybe other points a well.

**Comment by smals-chlo** [comment]
Hello @pvdbosch , 
I have made the adaptations from the Rest Design Workgroup of 9/9 and also from the comments of Smals Rest last week. 
Can you make a final review? 
FYI: @wsalembi

**Comment by smals-chlo** [comment]
Hello @pvdbosch , 
Have you seen my previous comment? 
Are you waiting something from me?

**Comment by pvdbosch** [comment]
Hi @smals-chlo , seen the comment but haven't gotten around to it yet. Still on my todo-list.

**Comment by smals-chlo** [comment]
I see that the changes are published now in the REST Guidelines, thanks @pvdbosch!
