### ISSUE TITLE
removing selection of items from a collection

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#65]
validate proposed changes in PR #64 about DELETE on a collection to remove a selection of items

**Comment by pvdbosch** [comment]
changes approved on WG. Keeping open until PR merged, which first needs some other changes (see #40).

**Comment by smals-chlo** [comment]
Hello @pvdbosch , 
I have made the adaptations from the Rest Design Workgroup of 9/9 and also from the comments of Smals Rest last week. 
Can you make a final review? 
FYI: @wsalembi

**Comment by pvdbosch** [comment]
merged PR, I'll publish new guide today
