### ISSUE TITLE
representing non-API-specific problems and headers in OpenAPI

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#67]
_non-API specific problems_

These responses may or may not have a Problem response payload.

Examples:
* 500 Internal Error - unexpectedly failure
* 502 Bad Gateway
* 400 Bad Request when request isn't valid wrt OAS spec.
* 401 / 403  AuthN/AuthZ problems
* 404 resource not found for path not defined in OAS
* 413 payload too large

How to represent this in OpenAPI/Swagger?
1) add Problem response for each status code (400,500,502,...) on each operation.
   This was done in the "/health" operation in common-v1.yaml
2)  Add a Problem schema as "default"  response (i.e. all unspecified statuscodes) on each operation
    Or, in OpenAPI 3, for "4xx" and "5xx" statuscodes if you want to limit it to error status codes only
3) omit it entirely.
   Should probably also be deleted then from "/health" in common-v1.yaml.

This somewhat reminds of discussions on checked and unchecked exceptions in Java. Personally, I'm in favor of option 3 so the OpenAPI files don't get cluttered.  Instead, you can refer to some general documentation from each OpenAPI file that explains this.

_headers (like trace IDs)_

When the BelGov-(-Related)-Trace-Id HTTP headers are supported, should they be specified in the OpenAPI file?
Same point can be raised for standard HTTP headers like Accept-Language.

Personally, I'm in favor of not doing so:
* it makes the OpenAPI files cluttered
* for code generation from OpenAPI, it generates additional method parameters while these would be easier to handler by a generic proxy/interceptor

**Comment by jpraet** [comment]
Question about whether or not to specify `BelGov-(-Related)-Trace-Id` HTTP headers in OpenAPI file also applies to `Accept-Language` HTTP header used for I18N.

**Comment by pvdbosch** [comment]
Related discussion in OpenAPI spec on global response definitions: https://github.com/OAI/OpenAPI-Specification/issues/521 ; hasn't reached a conclusion yet.

**Comment by pvdbosch** [comment]
for generic problems:
* defining problem for each status code is too verbose/cluttered => discarded
* omitting generic problems: could cause compatibility issues with openapi validators on reponse (e.g. atlassian openapi validator)
* "default" or "4xx"/"5xx"? => more compatible; "4xx"/"5xx" is correcter but more verbose while not preventing many real-life issues

=> preference of WG to use "default" with generic ProblemResponse

**Comment by pvdbosch** [comment]
for headers: don't specify them; only operation/logic-specific headers (like ETag)

**Comment by pvdbosch** [comment]
resolved with the merge of PR #100
