### ISSUE TITLE
Consistent uri notation in examples

### ISSUE THREAD

**Issue by wsalembi** [belgif/rest-guide#68]
Some examples use absolute URIs, others are abbreviated. We added a note (For brevity most URIs in examples are shortened, but in practice URIs should be in absolute notation.) at the start of the style guide but it isn't ery explicit.

Decide approach and adapt examples. 
Perhaps synchronized with the publication of our demo API on internet.

**Comment by pvdbosch** [comment]
Syncing the URIs with the demo API was indeed the plan, as mentioned in #19 :

 "Examples in the styleguide should be replaced with samples from the REST mock API; and using full URLs instead of relative ones."

**Comment by pvdbosch** [comment]
will be taken up in #19, closing this one
