### ISSUE TITLE
Typo in the REST Guidelines, Example 29. Resource links

### ISSUE THREAD

**Issue by hilsonp** [belgif/rest-guide#78]
The Example 29. Resource links has an error in the $ref used for PersonReference

https://www.gcloud.belgium.be/rest/#links

  PersonReference:
    allOf:
      - "$ref": "./common/v1/common-v1.yaml/definitions/HttpLink"

MUST be

  PersonReference:
    allOf:
      - "$ref": "./common/v1/common-v1.yaml#/definitions/HttpLink"

**Comment by pvdbosch** [comment]
thanks for reporting. Seems to be some asciidoc escaping issue because it's there in the source file ( https://raw.githubusercontent.com/belgif/rest-guide/master/src/main/asciidoc/hypermedia.adoc ). Will try to fix it.

**Comment by pvdbosch** [comment]
It is fixed in the sources of the guide. Also reviewed and updated other $ref values used in examples.

It will be updated on the website when next update of the guide is published.
