### ISSUE TITLE
move REST guide to belgif.be

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#91]
1.  **done** configure build pipeline with GitHub actions => @pvdbosch 
2.  **done** publish on belgif.be @barthanssens 
3. **done** update references to the website:  @pvdbosch 
* *done* on https://www.belgif.be/page/specifications.nl.html
* *done* in the guide itself:
  * README.md
  * throughout the guide; e.g. href values for problem examples
* *done* in openapi-problem and openapi-common (examples in the YAML files)  - released as v1.2.1
* *done* on https://www.gcloud.belgium.be/nl/service/detail/fsp
4. **done** configure redirect from gcloud.belgium.be to belgif.be (including subpages) => @zebby76 
5. **done** communicate relocation, request to update any internal sites/doc at participating organizations (Smals, CBSS, ...)
6. (optional) update L&F to belgif.be L&F => @barthanssens

**Comment by pvdbosch** [comment]
@barthanssens FYI, the [REST security guide](https://github.com/belgif/rest-security) will also need to be published on belgif.be at some point. It is currently still in draft and not yet published. It follows the same documentation structure (asciidoc) as this REST guide.

**Comment by pvdbosch** [comment]
I set up a build with GitHub actions: 
* to build locally, you can now simply execute `mvn` instead of `mvn site`. This will also create a zip with the htmls.
* there's a 'continuous integration' build on each repo change, and a 'release' build 
  * example GitHub actions release (as zip): https://github.com/belgif/rest-guide/releases/tag/untagged-28ac8f043c72c6b43455 (draft release, requires GitHub project permissions)
  * release instructions: https://github.com/belgif/rest-guide/blob/master/RELEASE.md

**Comment by pvdbosch** [comment]
Updated the REST-guide master branch to reference to belgif.be instead of G-Cloud.
@barthanssens could you update the version on belgif.be?

Note that REST JSON responses conform to the REST guide may return links to the problem web pages part of the guide (e.g. "href": "https://www.belgif.be/specification/rest/api-guide/problems/missingScope.html"). So these URLs should remain functioning, i.e. a redirect would need to be put in place if the URL ever changes.

**Comment by barthanssens** [comment]
ok, belgif.be has been updated

**Comment by pvdbosch** [comment]
@zebby76 , now that everything has been published on the new location, could you configure the redirection from https://www.gcloud.belgium.be/rest/ to https://www.belgif.be/specification/rest/api-guide/ ?

**Comment by zebby76** [comment]
@pvdbosch , redirection has been implemented : 

```nginx
rewrite ^/rest$ https://www.belgif.be/specification/rest/api-guide permanent;
rewrite ^/rest/(.*)$ https://www.belgif.be/specification/rest/api-guide/$1 permanent;
```

**Comment by pvdbosch** [comment]
openapi-problem and openapi-common 1.2.1 were released; communication was done and link on G-Cloud page ( https://www.gcloud.belgium.be/nl/service/detail/fsp ) was updated.

L&F can be updated at any time by BOSA; not blocking. We can consider this task as complete then.
