### ISSUE TITLE
Create resource: allow returning resource representation

### ISSUE THREAD

**Issue by wsalembi** [belgif/rest-guide#92]
https://www.gcloud.belgium.be/rest/#create-resource

AS-IS: The response contains an empty body.

TO-BE: The response either contains an empty body or the representation of the created resource.

**Comment by pvdbosch** [comment]
I agree to allow returning the resource. 
Other REST guidelines:
* zalando: empty or created resource: https://opensource.zalando.com/restful-api-guidelines/#json-guidelines
* nationale bank belgië: should return created resource: https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki/CRUD-Create-Single-item
* Microsoft: may return "full metadata": https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#741-post (I guess only identifier, name, ...)
* DigiPolis Antwerpen: optionally partial or full resource - https://antwerp-api.digipolis.be/#/content/developers/statuscodes-response

Maybe we can also allow partial resource to be returned (e.g. only generated identifier). Maybe some guidelines what to consider in this decision? Is it a large resource; are there any generated/default fields added, ...

**Comment by pvdbosch** [comment]
Conclusion of WG meeting 30/3, allow three response bodies:
* no response body
* partial resource (e.g. only generated resource identifiers)
* full resource

**Comment by pvdbosch** [comment]
PR was merged and being published
